services:
    web:
        container_name: front
        build:
            context: ./front

        environment:
            API_URL: http://192.168.1.4:3000

        restart: always
        ports:
            - 8080:8080
        networks:
            - my_network
    back:
        container_name: back
        build:
            context: ./back
        restart: always
        ports:
            - 3000:3000
        networks:
            - my_network
        secrets:
            - token
secrets:
    token:
        file: ./secrets/token.txt

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
    my_network:
        external: true